# Generated by Django 5.1.6 on 2025-02-19 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dbPokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Cerco'), (1, 'Offro')])),
                ('espansione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbPokemon.espansione')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbPokemon.pokemon')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scambi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scambio',
                'verbose_name_plural': 'Scambi',
            },
        ),
    ]
