# Generated by Django 5.1.6 on 2025-02-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espansione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('isScambiAttivi', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Espansione',
                'verbose_name_plural': 'Espansioni',
            },
        ),
        migrations.CreateModel(
            name='Rarita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('isScambiAttivi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rarità',
                'verbose_name_plural': 'Rarità',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('isScambiabile', models.BooleanField(default=False)),
                ('espansione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='dbPokemon.espansione')),
                ('rarita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbPokemon.rarita')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
            },
        ),
    ]
