# Generated by Django 5.1.6 on 2025-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbPokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokedex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
